### ISSUE TITLE
Ladok grading

### ISSUE THREAD

**Issue by pierrelefevre** [KTH/programmable-society#102]
Hey all! 
I was going to do the open source contribution for the Jan deadline. 

However I just received the final grade on canvas. Will this be updated in january or did something go wrong?

Best
Pierre

**Comment by fabianzeiher** [comment]
Same here :)

**Comment by monperrus** [comment]
great, looking forward to it!

**Comment by monperrus** [comment]
@pierrelefevre @cetceeve to close Ladok grading, let us know about the update on the open source task. Thanks!

**Comment by pierrelefevre** [comment]
Didn't hear back from the maintainers on my PR so I'll skip the task unfortunately 😔

**Comment by monperrus** [comment]
ack, there is a 🎁 in Ladok for you

**Comment by fabianzeiher** [comment]
@monperrus Happy to report that my open-source contribution was merged last week, see #107
