### ISSUE TITLE
Wording in grading-criteria.md

### ISSUE THREAD

**Issue by pierrelefevre** [KTH/programmable-society#36]
Hi!
Seems the wording for the types of examination is a bit off if my understanding is correct that these should be carried out individually, except for the smart contract project. Maybe this is left over from the DevOps course?

Examples with "students"
- (examination rules) submission from the original **authors**
- (presentation) All **students** in a presentation [...] 
- (essay) The **students** write an essay

Examples with "you"
- (feedback) **you** provide constructive
- (open-source) **you** contribute to one open-source

Best,
Pierre

**Comment by bbaudry** [comment]
Thanks @pierrelefevre for pointing this.
It's fixed
