### ISSUE TITLE
Week 6: Questions

### ISSUE THREAD

**Issue by filippaleuckfeld** [KTH/programmable-society#86]
Here we post the questions we ask live during the lecture of Week 6. Please follow the following format:

```
Title of presentation or demo
Question(s)
KTH ID
```

**Comment by pierrelefevre** [comment]
Blockchain monitoring, incident response with Open zeppelin defender
Why use a relayer for pausing the contract?
pierrelf

**Comment by filippaleuckfeld** [comment]
[Private PoA Ethereum Blockchain Network](https://github.com/KTH/programmable-society/tree/2023/contributions/demo/week6/vivia)
Can you use another consensus mechanism than proof of authority?
efle

**Comment by vivi365** [comment]
#85 Alchemy Notify and NFT API
How do you handle your secret keys?
vivia

**Comment by flaxxen** [comment]
Proof of stake vs. Proof of work

How large does the stake/penalty need to be to prevent malicious behavior?
Felixq

**Comment by ChristoferVikstroem** [comment]
Comparative Analysis of Two Consensus Mechanisms: Proof of Stake (PoS) vs. Proof of Work (PoW)
Compared to PoA, do you know the differences in energy consumption and security for PoS and PoW?
chrvik

**Comment by lerjevik** [comment]
Blockchain monitoring, incident response with Open zeppelin defender
What is Open Zeppelin Defender 2.0? What functionality does it add?
lerjevik

**Comment by alegust** [comment]
Proof of stake vs. Proof of work
Is one more widely used?
algust

**Comment by rsssss12** [comment]
Showcasing Alchemy Notify API & NFT API
Is it sufficient to be careful to prevent airdrop scams
rscholz

**Comment by fabianzeiher** [comment]
Proof of stake vs Proof of work
More of a comment on network partitions and "traditional" consensus algorithms that turned out more relevant than I thought.

Scientific Work in the Blockchain Space
Is there a performance penalty from composing smart contract?

zeiher

**Comment by oskarsva** [comment]
Proof of stake vs. Proof of work
if we consider the impossibility results of byzantine consensus in distributed systems. 
What guarantees do we get from PoS and PoW? Can we guarantee that the algorithm converges for instance?

oskarsva

**Comment by sifisKoen** [comment]
# Name: Iosif Koen

### Questions

* BitCoin vs Ethereum (Ethereum is better than BitCoin but is it actual the future? When we see more and more big players go closer and closer to BitCoin, that creates the question are they wrong? Or actually BitCoin is the future?).
* Ask if Martin's paper [Neural Transfer Learning for Repairing Security Vulnerabilities in C Code](https://ieeexplore.ieee.org/document/9699412) can apply to other languages to.

### Contributions

* Geth (go-ethereum)
     Talk and add some interesting information about Geth, and some fun facts.
* Explain how and why we can interact with **Javascript** console via Geth (Geth comes with this functionality).
     Talk with Martin about Lua and how it get replaced from Go, Javascript.
* Add how a window manager works/programming with the help of Martin.
     Talk how to manage a tilling window manager and in what languages we can program them (Qtile: Python)
     This is relevant with the implemented consoles and how they work (Martin mentioned Lua was the main language that used to be used for those tasks)

**Comment by edvinbaggman** [comment]
Showcasing Alchemy Notify API & NFT API
How does this notifications prevent the type of scam that was presented? We still get the nft
Baggman
